import { applicantProfileBundleSchema, DEMO_PROFILE_ID, type ApplicantProfileBundle } from "@applyqueue/shared";

const timestamp = "2026-09-20T03:22:15.123+00:00";

export function makeProfileBundle(): ApplicantProfileBundle {
  return applicantProfileBundleSchema.parse({
    profile: {
      id: DEMO_PROFILE_ID,
      first_name: "Ada",
      last_name: "Lovelace",
      preferred_name: "Ada",
      email: "ada@example.com",
      phone: "+1 416 555 0100",
      address_line_1: "123 King Street West",
      city: "Toronto",
      state_province: "Ontario",
      postal_code: "M5V 1A1",
      country: "Canada",
      timezone: "America/Toronto",
      graduation_date: "May 2027",
      work_authorization: "Authorized to work in Canada",
      requires_sponsorship: false,
      willing_to_relocate: true,
      preferred_locations: ["Toronto", "New York"],
      availability_start_date: "2027-05-01",
      short_bio: "Computer science student interested in reliable software systems.",
      created_at: timestamp,
      updated_at: timestamp,
    },
    educations: [
      {
        id: "6bc78fa6-42f3-4eeb-95d8-ff37ccefe13f",
        profile_id: DEMO_PROFILE_ID,
        school: "University of Waterloo",
        degree: "Bachelor of Mathematics",
        field_of_study: "Computer Science",
        start_month: 9,
        start_year: 2023,
        end_month: 5,
        end_year: 2027,
        is_current: true,
        created_at: timestamp,
        updated_at: timestamp,
      },
      {
        id: "31a43c18-3c0a-405a-8843-e6d84ac2dc12",
        profile_id: DEMO_PROFILE_ID,
        school: "Example Secondary School",
        end_year: 2023,
        is_current: false,
        created_at: timestamp,
        updated_at: timestamp,
      },
    ],
    employments: [
      {
        id: "e7069733-85d8-4285-bcb6-5f2e1cfc84b5",
        profile_id: DEMO_PROFILE_ID,
        company: "Analytical Engines",
        title: "Software Engineering Intern",
        location: "Toronto, Ontario",
        start_month: 5,
        start_year: 2026,
        is_current: true,
        description: "Built reliable internal tools.",
        created_at: timestamp,
        updated_at: timestamp,
      },
    ],
    links: [
      {
        id: "06403c78-8fc7-4a05-9a67-c58a12233dcb",
        profile_id: DEMO_PROFILE_ID,
        type: "LINKEDIN",
        label: "LinkedIn",
        url: "https://linkedin.com/in/ada",
        created_at: timestamp,
        updated_at: timestamp,
      },
      {
        id: "a56a28f9-b729-4ab7-969a-a596a26c838b",
        profile_id: DEMO_PROFILE_ID,
        type: "GITHUB",
        label: "GitHub",
        url: "https://github.com/ada",
        created_at: timestamp,
        updated_at: timestamp,
      },
    ],
    documents: [{
      id: "cd7c6c8c-8f45-4abf-8b4c-b834e906ea08",
      profile_id: DEMO_PROFILE_ID,
      type: "RESUME",
      storage_path: `profiles/${DEMO_PROFILE_ID}/resume/ada.pdf`,
      filename: "ada-resume.pdf",
      mime_type: "application/pdf",
      file_size_bytes: 4096,
      is_primary: true,
      created_at: timestamp,
      updated_at: timestamp,
    }],
  });
}
